#region AutoGeneratedHeader

// TactileCs :: Point.cs last updated by: Ryan Hughes
// File last updated at: 19:35:38 on 02-12-2025
// Parent solution for file: TactileCs, file originally created at 19:12:37 on 02-12-2025 as part of project TactileCs.

#endregion


// ReSharper disable CompareOfFloatsByEqualityOperator

using System.Numerics;


namespace TactileCs.Geometry;


/// <summary>
/// Represents a 2D point with double-precision coordinates.
/// </summary>
public class Point {

	/// <summary>
	/// The X coordinate.
	/// </summary>
	public double X { get; set; }

	/// <summary>
	/// The Y coordinate.
	/// </summary>
	public double Y { get; set; }


	/// <summary>
	/// Creates a new <see cref="Point"/> that is a copy of <paramref name="other"/>.
	/// </summary>
	/// <param name="other">The point to clone.</param>
	/// <returns>A new <see cref="Point"/> with the same coordinates as <paramref name="other"/>.</returns>
	public Point Clone(Point other) => new(other.X, other.Y);


	/// <summary>
	/// Represents a 2D point with double-precision coordinates.
	/// </summary>
	/// <param name="x">The X coordinate of the point.</param>
	/// <param name="y">The Y coordinate of the point.</param>
	public Point(double x, double y) {
		X = x;
		Y = y;
	}


	/// <summary>
	/// Create a new <see cref="Point"/> from the given <see cref="Vector2"/>.
	/// </summary>
	/// <param name="vector">The vector to convert.</param>
	/// <returns>A new Point.</returns>
	public Point(Vector2 vector) {
		X = vector.X;
		Y = vector.Y;
	}


	/// <summary>
	/// Computes the Euclidean distance to <paramref name="other"/>.
	/// </summary>
	/// <param name="other">The target point.</param>
	/// <returns>The straight-line distance between this point and <paramref name="other"/>.</returns>
	public double DistanceTo(Point other) {
		double dx = X - other.X;
		double dy = Y - other.Y;

		return Math.Sqrt((dx * dx) + (dy * dy));
	}


	/// <summary>
	/// Returns a new point translated by the specified offsets.
	/// </summary>
	/// <param name="dx">Translation along the X axis.</param>
	/// <param name="dy">Translation along the Y axis.</param>
	/// <returns>A translated <see cref="Point"/>.</returns>
	public Point Translate(double dx, double dy) => new(X + dx, Y + dy);


	/// <summary>
	/// Returns a new point translated by the specified vector.
	/// </summary>
	/// <param name="v">The translation vector.</param>
	/// <returns>A translated <see cref="Point"/>.</returns>
	public Point Translate(Vector2 v) => new(X + v.X, Y + v.Y);


	/// <summary>
	/// Determines whether both coordinates are finite numbers (not NaN or Infinity).
	/// </summary>
	/// <returns><c>true</c> if both coordinates are valid; otherwise <c>false</c>.</returns>
	public bool IsValid() => !double.IsNaN(X) && !double.IsNaN(Y) && !double.IsInfinity(X) && !double.IsInfinity(Y);


	/// <summary>
	/// Determines whether the point is exactly at the origin (0,0).
	/// </summary>
	/// <returns><c>true</c> if both coordinates are zero; otherwise <c>false</c>.</returns>
	public bool IsZero() => (X == 0) && (Y == 0);


	/// <summary>
	/// Determines whether this point has exactly the same coordinates as <paramref name="other"/>.
	/// </summary>
	/// <param name="other">The point to compare.</param>
	/// <returns><c>true</c> if both coordinates are equal; otherwise <c>false</c>.</returns>
	public bool Equals(Point other) => (X == other.X) && (Y == other.Y);


	/// <summary>
	/// Determines whether this point is approximately equal to <paramref name="other"/> using <see cref="Constants.PositionEpsilon"/>.
	/// </summary>
	/// <param name="other">The point to compare.</param>
	/// <returns><c>true</c> if both coordinate differences are within the epsilon; otherwise <c>false</c>.</returns>
	public bool AlmostEqual(Point other) => (Math.Abs(X - other.X) < Constants.PositionEpsilon) && (Math.Abs(Y - other.Y) < Constants.PositionEpsilon);


	/// <summary>
	/// Determines whether this point is within <see cref="Constants.DistanceEpsilon"/> of <paramref name="other"/>.
	/// </summary>
	/// <param name="other">The point to compare.</param>
	/// <returns><c>true</c> if the distance is less than the epsilon; otherwise <c>false</c>.</returns>
	public bool IsCloseTo(Point other) => DistanceTo(other) < Constants.DistanceEpsilon;


	/// <summary>
	/// Returns a readable representation of the point.
	/// </summary>
	/// <returns>A string in the form "Point (X, Y)".</returns>
	public override string ToString() => $"Point ({X}, {Y})";

}