#region AutoGeneratedHeader

// TactileCs :: Polygon.cs last updated by: Ryan Hughes
// File last updated at: 19:13:35 on 02-12-2025
// Parent solution for file: TactileCs, file originally created at 19:12:35 on 02-12-2025 as part of project TactileCs.

#endregion


// Port of concepts from Tactile (c) 2018 Craig S. Kaplan, BSD 3-Clause. See LICENSE.

#pragma warning disable IDE0028


namespace TactileCs.Geometry;


/// <summary>
/// Simple polygon represented by an ordered list of vertices.
/// </summary>
/// <param name="vertices">
/// An enumerable sequence of 2D points that define the polygon's vertices in order.
/// The sequence is copied into an internal list; subsequent changes to the original
/// enumerable do not affect this instance.
/// </param>
public sealed class Polygon(IEnumerable<Vector2> vertices) {

	/// <summary>
	/// Gets the polygon's vertices as a read-only list.
	/// The returned collection is a read-only view over the internal vertex list;
	/// callers must not attempt to modify the collection contents.
	/// </summary>
	public IReadOnlyList<Vector2> Vertices {
		get {
			return _Vertices;
		}
	}

	/// <summary>
	/// Internal storage for the polygon's vertices.
	/// Initialized from the constructor parameter `vertices`.
	/// </summary>
	readonly List<Vector2> _Vertices = new(vertices);

	/// <summary>
	/// Gets the number of vertices in the polygon.
	/// </summary>
	public int Count {
		get {
			return _Vertices.Count;
		}
	}

	/// <summary>
	/// Gets the total length of the polygon's loop (perimeter). Computed as the sum of the lengths of each edge connecting consecutive vertices, forming a closed loop.
	/// </summary>
	/// <returns>The total length of the polygon's loop.</returns>
	public double LoopLength {
		get {
			double length = 0.0;

			for (int i = 0; i < _Vertices.Count; i++) {
				Vector2 a = _Vertices[i];
				Vector2 b = _Vertices[(i + 1) % _Vertices.Count];
				length += (b - a).Length;
			}

			return length;
		}
	}

	/// <summary>
	/// Gets the polygon's area.
	/// </summary>
	/// <value>The absolute area enclosed by the polygon.</value>
	/// <remarks>
	/// The area is computed using the shoelace formula:
	/// Area = 0.5 * |sum_{i=0}^{n-1} (x_i * y_{i+1} - x_{i+1} * y_i)|.
	/// Vertices are interpreted as forming a closed loop; the index wraps from the last vertex back to the first.
	/// Time complexity: O(n) where n is the number of vertices.
	/// </remarks>
	public double Area {
		get {
			double area = 0.0;

			for (int i = 0; i < _Vertices.Count; i++) {
				Vector2 a = _Vertices[i];
				Vector2 b = _Vertices[(i + 1) % _Vertices.Count];
				area += a.X * b.Y;
				area -= b.X * a.Y;
			}

			return Math.Abs(area) / 2.0;
		}
	}


	/// <summary>
	/// Tests whether the polygon is self-intersecting.
	/// </summary>
	/// <returns>
	/// <c>true</c> if any two non-adjacent edges of the polygon intersect or touch;
	/// otherwise, <c>false</c>.
	/// </returns>
	/// <remarks>
	/// The algorithm checks every pair of non-adjacent edges for intersection using the <see cref="SegmentsIntersect"/> helper.
	/// Adjacent edges and the pair formed by the first and last edge are skipped appropriately.
	/// Time complexity: O(n^2) in the number of vertices.
	/// </remarks>
	public bool IsSelfIntersecting() {
		int n = _Vertices.Count;

		for (int i = 0; i < n; i++) {
			Point a1 = new(_Vertices[i]);
			Point a2 = new(_Vertices[(i + 1) % n]);

			for (int j = i + 2; j < n; j++) {
				// Skip adjacent edges
				if ((j == ((i + 1) % n)) || ((i == 0) && (j == (n - 1)))) {
					continue;
				}

				Point b1 = new(_Vertices[j]);
				Point b2 = new(_Vertices[(j + 1) % n]);

				if (SegmentsIntersect(a1, a2, b1, b2)) {
					return true;
				}
			}
		}

		return false;
	}


	/// <summary>
	/// Determines whether two closed line segments intersect.
	/// </summary>
	/// <param name="a1">The first endpoint of the first segment.</param>
	/// <param name="a2">The second endpoint of the first segment.</param>
	/// <param name="b1">The first endpoint of the second segment.</param>
	/// <param name="b2">The second endpoint of the second segment.</param>
	/// <returns>
	/// <c>true</c> if the segments intersect or touch (including endpoint touches and co-linear overlapping);
	/// otherwise, <c>false</c>.
	/// </returns>
	/// <remarks>
	/// The implementation uses orientation tests (cross products) to detect proper intersections and a bounding-box (on-segment) check for co-linear overlap and endpoint-touching cases.
	/// Segments are treated as closed (endpoints count as intersections). A small epsilon is applied to handle floating-point imprecision.
	/// </remarks>
	public static bool SegmentsIntersect(Point a1, Point a2, Point b1, Point b2) {
		const double eps = Constants.PositionEpsilonDefault;

		double o1 = Orient(a1, a2, b1);
		double o2 = Orient(a1, a2, b2);
		double o3 = Orient(b1, b2, a1);
		double o4 = Orient(b1, b2, a2);

		// General case: proper intersection
		if ((((o1 > eps) && (o2 < -eps)) || ((o1 < -eps) && (o2 > eps))) && (((o3 > eps) && (o4 < -eps)) || ((o3 < -eps) && (o4 > eps)))) {
			return true;
		}

		// Special cases: Co-linear and on-segment
		if ((Math.Abs(o1) <= eps) && OnSegment(a1, a2, b1, eps)) {
			return true;
		}

		if ((Math.Abs(o2) <= eps) && OnSegment(a1, a2, b2, eps)) {
			return true;
		}

		if ((Math.Abs(o3) <= eps) && OnSegment(b1, b2, a1, eps)) {
			return true;
		}

		return (Math.Abs(o4) <= eps) && OnSegment(b1, b2, a2, eps);
	}


	/// <summary>
	/// Determines whether a point <paramref name="r"/> lies on the closed line segment defined by endpoints <paramref name="p"/> and <paramref name="q"/>, within a specified tolerance.
	/// </summary>
	/// <param name="p">The first endpoint of the segment.</param>
	/// <param name="q">The second endpoint of the segment.</param>
	/// <param name="r">The point to test for lying on the segment. This method assumes <paramref name="r"/> is co-linear with <paramref name="p"/> and <paramref name="q"/> (within an orientation epsilon).</param>
	/// <param name="epsLocal">A non-negative tolerance value used to expand the bounding box to account for floating-point imprecision.</param>
	/// <returns>
	/// <c>true</c> if <paramref name="r"/> lies within the inclusive bounding box of the segment [<paramref name="p"/>, <paramref name="q"/>] after applying <paramref name="epsLocal"/>; otherwise, <c>false</c>.
	/// </returns>
	/// <remarks>
	/// This is a fast, robust on-segment test that assumes co-linearity has been checked separately (for example using <see cref="Orient"/>).
	/// The method treats the segment as closed (endpoints count as on-segment). The tolerance <paramref name="epsLocal"/> is applied to both
	/// X and Y axes to accommodate numerical rounding errors. For correct behavior in edge cases, ensure <paramref name="epsLocal"/> is
	/// chosen consistently with other orientation/epsilon checks.
	/// </remarks>
	public static bool OnSegment(Point p, Point q, Point r, double epsLocal) {
		// Assume r is co-linear with p-q. Check if r lies within bounding box of p and q.
		double minX = Math.Min(p.X, q.X) - epsLocal;
		double maxX = Math.Max(p.X, q.X) + epsLocal;
		double minY = Math.Min(p.Y, q.Y) - epsLocal;
		double maxY = Math.Max(p.Y, q.Y) + epsLocal;

		return (r.X >= minX) && (r.X <= maxX) && (r.Y >= minY) && (r.Y <= maxY);
	}


	/// <summary>
	/// Computes the signed orientation (twice the signed area) of the triangle (p, q, r).
	/// </summary>
	/// <param name="p">The first point of the triangle.</param>
	/// <param name="q">The second point of the triangle.</param>
	/// <param name="r">The third point of the triangle.</param>
	/// <returns>
	/// A positive value if the sequence (p, q, r) is counter-clockwise, negative if clockwise, and zero if co-linear.
	/// The returned value equals the 2D cross product (q - p) x (r - p).
	/// </returns>
	public static double Orient(Point p, Point q, Point r) => ((q.X - p.X) * (r.Y - p.Y)) - ((q.Y - p.Y) * (r.X - p.X));


	/// <summary>
	/// Indicates whether the polygon has the minimum required number of vertices to represent a valid polygon.
	/// </summary>
	/// <returns><c>true</c> if the polygon has at least three vertices; otherwise, <c>false</c>.</returns>
	public bool IsValid() => _Vertices.Count >= 3;


	/// <summary>
	/// Computes the winding orientation of the polygon's vertex ordering.
	/// </summary>
	/// <returns>
	/// <see cref="Orientation.CounterClockwise"/> if the vertex ordering is counter-clockwise;
	/// otherwise, <see cref="Orientation.Clockwise"/>.
	/// </returns>
	/// <remarks>
	/// The method sums edge contributions (a standard signed-area related test). The sign of the accumulated sum
	/// determines the winding direction. The algorithm runs in O(n) time.
	/// </remarks>
	public Orientation GetOrientation() {
		double sum = 0.0;

		for (int i = 0; i < _Vertices.Count; i++) {
			Vector2 a = _Vertices[i];
			Vector2 b = _Vertices[(i + 1) % _Vertices.Count];
			sum += (b.X - a.X) * (b.Y + a.Y);
		}

		return sum > 0.0 ? Orientation.CounterClockwise : Orientation.Clockwise;
	}


	/// <summary>
	/// Determines if the polygon's vertices are ordered in a clockwise manner.
	/// </summary>
	/// <returns>True if the vertices are ordered clockwise; otherwise, false.</returns>
	public bool IsClockwise() => GetOrientation() == Orientation.Clockwise;


	/// <summary>
	/// Determines if the polygon's vertices are ordered in a counter-clockwise manner.
	/// </summary>
	/// <returns>True if the vertices are ordered counter-clockwise; otherwise, false.</returns>
	public bool IsCounterClockwise() => GetOrientation() == Orientation.CounterClockwise;


	/// <summary>
	/// Returns a new <see cref="Polygon"/> whose vertices are the result of applying
	/// the specified 2D transform to each vertex of this polygon.
	/// </summary>
	/// <param name="t">The transform to apply to each vertex.</param>
	/// <returns>
	/// A new <see cref="Polygon"/> containing the transformed vertices, in the same order.
	/// </returns>
	public Polygon Transform(Transform2D t) => new(_Vertices.Select(t.Apply));


	/// <summary>
	/// Enumeration representing the orientation of a polygon's vertices.
	/// </summary>
	public enum Orientation {

		Clockwise,
		CounterClockwise

	}


	/// <summary>
	/// Returns a string representation of the polygon as the coordinates of each vertex, formatted to six decimal places.
	/// </summary>
	public override string ToString() => $"Polygon [[{string.Join(", ", _Vertices.Select(static v => $"[{v.X:F6}, {v.Y:F6}]"))}]]";

}