#region AutoGeneratedHeader

// TactileCs :: Transform2D.cs last updated by: Ryan Hughes
// File last updated at: 19:07:05 on 02-12-2025
// Parent solution for file: TactileCs, file originally created at 19:12:04 on 02-12-2025 as part of project TactileCs.

	#endregion


// Port of concepts from Tactile (c) 2018 Craig S. Kaplan, BSD 3-Clause. See LICENSE.

namespace TactileCs.Geometry;


/// <summary>
/// A 2D affine transform represented as the top two rows of a square matrix
/// such that applying the transform to a point (x, y) is done via:
/// [ x' ]   [ A  B  C ]   [ x ]
/// [ y' ] = [ D  E  F ] * [ y ]
/// [ 1  ]   [ 0  0  1 ]   [ 1 ]
/// or equivalently: (x', y') = (Ax + By + C, Dx + Ey + F)
///
/// This struct is immutable.
/// </summary>
public readonly struct Transform2D {

	/// <summary>
	/// Matrix element at row 0, column 0 (A).
	/// </summary>
	public double A {
		get;
	}

	/// <summary>
	/// Matrix element at row 0, column 1 (B).
	/// </summary>
	public double B {
		get;
	}

	/// <summary>
	/// Matrix element at row 0, column 2 (C). This element represents the translation
	/// component applied to the x coordinate.
	/// </summary>
	public double C {
		get;
	}

	/// <summary>
	/// Matrix element at row 1, column 0 (D).
	/// </summary>
	public double D {
		get;
	}

	/// <summary>
	/// Matrix element at row 1, column 1 (E).
	/// </summary>
	public double E {
		get;
	}

	/// <summary>
	/// Matrix element at row 1, column 2 (F). This element represents the translation
	/// component applied to the y coordinate.
	/// </summary>
	public double F {
		get;
	}

	/// <summary>
	/// The identity transform.
	/// </summary>
	/// <returns>
	/// A <see cref="Transform2D"/> equivalent to the 3x3 identity matrix:
	/// [1 0 0; 0 1 0; 0 0 1]. Applying this transform leaves points unchanged.
	/// </returns>
	public static Transform2D Identity {
		get {
			return new Transform2D(1, 0, 0, 0, 1, 0);
		}
	}


	/// <summary>
	/// Creates a new affine transform from the specified matrix elements.
	/// </summary>
	/// <param name="a">Element at row 0, column 0.</param>
	/// <param name="b">Element at row 0, column 1.</param>
	/// <param name="c">Element at row 0, column 2 (x translation).</param>
	/// <param name="d">Element at row 1, column 0.</param>
	/// <param name="e">Element at row 1, column 1.</param>
	/// <param name="f">Element at row 1, column 2 (y translation).</param>
	/// <remarks>
	/// The struct is immutable; the provided values are stored and cannot be changed after construction.
	/// The internal representation corresponds to the top two rows of a 3x3 homogeneous transform matrix.
	/// </remarks>
	public Transform2D(double a,
					   double b,
					   double c,
					   double d,
					   double e,
					   double f) {
		A = a;
		B = b;
		C = c;
		D = d;
		E = e;
		F = f;
	}


	/// <summary>
	/// Apply this transform to a point.
	/// </summary>
	/// <param name="p">The point to transform.</param>
	/// <returns>
	/// A new <see cref="Vector2"/> containing the transformed coordinates computed as:
	/// (x', y') = (Ax + By + C, Dx + Ey + F).
	/// </returns>
	public Vector2 Apply(Vector2 p) {
		double x = (A * p.X) + (B * p.Y) + C;
		double y = (D * p.X) + (E * p.Y) + F;

		return new Vector2(x, y);
	}


	/// <summary>
	/// Compose two transforms: t1 ∘ t2 (apply <paramref name="t2"/> first, then <paramref name="t1"/>).
	/// </summary>
	/// <param name="t1">The transform applied second (outer transform).</param>
	/// <param name="t2">The transform applied first (inner transform).</param>
	/// <returns>
	/// A new <see cref="Transform2D"/> that is the composition of <paramref name="t1"/>
	/// and <paramref name="t2"/>. The result is equivalent to matrix multiplication of
	/// the 3x3 homogeneous matrices represented by the inputs.
	/// </returns>
	public static Transform2D Multiply(Transform2D t1, Transform2D t2) {
		double a = (t1.A * t2.A) + (t1.B * t2.D);
		double b = (t1.A * t2.B) + (t1.B * t2.E);
		double c = (t1.A * t2.C) + (t1.B * t2.F) + t1.C;
		double d = (t1.D * t2.A) + (t1.E * t2.D);
		double e = (t1.D * t2.B) + (t1.E * t2.E);
		double f = (t1.D * t2.C) + (t1.E * t2.F) + t1.F;

		return new Transform2D(a, b, c, d, e, f);
	}


	/// <summary>
	/// Returns a string representation of the transform with six decimal places for each element.
	/// </summary>
	/// <returns>A formatted string of the form: [[A, B, C], [D, E, F]].</returns>
	public override string ToString() => $"Transform [[{A:F6}, {B:F6}, {C:F6}], [{D:F6}, {E:F6}, {F:F6}]]";

}