using System.Diagnostics.CodeAnalysis;

using static TactileCs.Geometry.Constants;


#region AutoGeneratedHeader

// TactileCs :: Vector2.cs last updated by: Ryan Hughes
// File last updated at: 18:44:30 on 02-12-2025
// Parent solution for file: TactileCs, file originally created at 18:12:30 on 02-12-2025 as part of project TactileCs.

#endregion


// Port of concepts from Tactile (c) 2018 Craig S. Kaplan, BSD 3-Clause. See LICENSE.


namespace TactileCs.Geometry;


/// <summary>
/// A 2D vector with double-precision components.
/// </summary>
/// <param name="x">The X component.</param>
/// <param name="y">The Y component.</param>
public readonly struct Vector2(double x, double y) : IEquatable<Vector2> {

	/// <summary>
	/// The X component of the vector.
	/// </summary>
	public double X {
		get;
	} = x;

	/// <summary>
	/// The Y component of the vector.
	/// </summary>
	public double Y {
		get;
	} = y;

	/// <summary>
	/// The squared length (magnitude) of the vector. Prefer when comparing lengths to avoid the sqrt cost.
	/// </summary>
	public double LengthSquared {
		get {
			return (X * X) + (Y * Y);
		}
	}

	/// <summary>
	/// The length (magnitude) of the vector.
	/// </summary>
	public double Length {
		get {
			return Math.Sqrt(LengthSquared);
		}
	}

	/// <summary>
	/// A vector with both components set to zero.
	/// </summary>
	public static Vector2 Zero {
		get {
			return new Vector2(0.0, 0.0);
		}
	}

	/// <summary>
	/// A vector with both components set to one.
	/// </summary>
	public static Vector2 One {
		get {
			return new Vector2(1.0, 1.0);
		}
	}

	/// <summary>
	/// The unit X vector (1, 0).
	/// </summary>
	public static Vector2 UnitX {
		get {
			return new Vector2(1.0, 0.0);
		}
	}

	/// <summary>
	/// The unit Y vector (0, 1).
	/// </summary>
	public static Vector2 UnitY {
		get {
			return new Vector2(0.0, 1.0);
		}
	}


	/// <summary>
	/// Returns the dot product of this vector with another.
	/// </summary>
	/// <param name="other">The other vector.</param>
	/// <returns>The scalar dot product.</returns>
	public double Dot(in Vector2 other) => (X * other.X) + (Y * other.Y);


	/// <summary>
	/// Returns the dot product of two vectors.
	/// </summary>
	/// <param name="a">First vector.</param>
	/// <param name="b">Second vector.</param>
	/// <returns>The scalar dot product.</returns>
	public static double Dot(in Vector2 a, in Vector2 b) => (a.X * b.X) + (a.Y * b.Y);


	/// <summary>
	/// Returns the 2D cross product (z-component of the 3D cross product) of this vector with another.
	/// </summary>
	/// <param name="other">The other vector.</param>
	/// <returns>The scalar cross product (X * other.Y - Y * other.X).</returns>
	public double Cross(in Vector2 other) => (X * other.Y) - (Y * other.X);


	/// <summary>
	/// Returns the 2D cross product (z-component of the 3D cross product) of two vectors.
	/// </summary>
	/// <param name="a">First vector.</param>
	/// <param name="b">Second vector.</param>
	/// <returns>The scalar cross product (a.X * b.Y - a.Y * b.X).</returns>
	public static double Cross(in Vector2 a, in Vector2 b) => (a.X * b.Y) - (a.Y * b.X);


	/// <summary>
	/// Returns a normalized (unit length) copy of this vector. If the vector is zero-length, the zero vector is returned.
	/// </summary>
	/// <returns>A unit-length copy of this vector, or <see cref="Zero"/> if this vector is zero-length.</returns>
	public Vector2 Normalized() {
		double len = Length;

		// Avoid division by zero.
		return len <= double.Epsilon ? Zero : new Vector2(X / len, Y / len);
	}


	/// <summary>
	/// Returns a vector perpendicular to this vector (rotated 90 degrees counter-clockwise).
	/// </summary>
	/// <returns>A perpendicular vector (-Y, X).</returns>
	public Vector2 Perpendicular() => new(-Y, X);


	/// <summary>
	/// Returns the angle of this vector in radians, measured counter-clockwise from the positive X axis.
	/// </summary>
	/// <returns>The angle in radians, in the range [-π, π].</returns>
	public double Angle() => Math.Atan2(Y, X);


	/// <summary>
	/// Returns the angle in radians between this vector and another vector.
	/// </summary>
	/// <param name="other">The other vector.</param>
	/// <returns>The angle between the vectors in radians, in the range [0, π].</returns>
	public double AngleTo(in Vector2 other) {
		double dot   = Dot(other);
		double cross = Cross(other);

		return Math.Atan2(cross, dot);
	}


	/// <summary>
	/// Linearly interpolates between this vector and another.
	/// </summary>
	/// <param name="other">The target vector.</param>
	/// <param name="t">The interpolation factor, typically in the range [0, 1].</param>
	/// <returns>A vector interpolated between this and <paramref name="other"/>.</returns>
	public Vector2 Lerp(in Vector2 other, double t) => new(X + ((other.X - X) * t), Y + ((other.Y - Y) * t));


	/// <summary>
	/// Returns the reflection of this vector across a normal vector.
	/// </summary>
	/// <param name="normal">The normal vector to reflect across (should be normalized).</param>
	/// <returns>The reflected vector.</returns>
	public Vector2 Reflect(in Vector2 normal) {
		double dot = Dot(normal);

		return new Vector2(X - (2.0 * dot * normal.X), Y - (2.0 * dot * normal.Y));
	}


	/// <summary>
	/// Returns this vector rotated by the specified angle in radians.
	/// </summary>
	/// <param name="radians">The rotation angle in radians.</param>
	/// <returns>The rotated vector.</returns>
	public Vector2 Rotate(double radians) {
		double cos = Math.Cos(radians);
		double sin = Math.Sin(radians);

		return new Vector2((X * cos) - (Y * sin), (X * sin) + (Y * cos));
	}


	/// <summary>
	/// Returns the distance between two vectors.
	/// </summary>
	/// <param name="a">First vector.</param>
	/// <param name="b">Second vector.</param>
	/// <returns>The Euclidean distance between <paramref name="a"/> and <paramref name="b"/>.</returns>
	public static double Distance(in Vector2 a, in Vector2 b) => (a - b).Length;


	/// <summary>
	/// Returns the squared distance between two vectors.
	/// </summary>
	/// <param name="a">First vector.</param>
	/// <param name="b">Second vector.</param>
	/// <returns>The squared Euclidean distance between <paramref name="a"/> and <paramref name="b"/>.</returns>
	public static double DistanceSquared(in Vector2 a, in Vector2 b) => (a - b).LengthSquared;


	/// <summary>
	/// Returns the distance from this vector to another.
	/// </summary>
	/// <param name="other">The other vector.</param>
	/// <returns>The Euclidean distance.</returns>
	public double Distance(in Vector2 other) => (this - other).Length;


	/// <summary>
	/// Returns the squared distance from this vector to another.
	/// </summary>
	/// <param name="other">The other vector.</param>
	/// <returns>The squared Euclidean distance.</returns>
	public double DistanceSquared(in Vector2 other) => (this - other).LengthSquared;


	/// <summary>
	/// Returns the component-wise sum of this vector and <paramref name="other"/>.
	/// </summary>
	/// <param name="other">The vector to add.</param>
	/// <returns>The resulting vector.</returns>
	public Vector2 Add(in Vector2 other) => new(X + other.X, Y + other.Y);


	/// <summary>
	/// Returns the component-wise difference of this vector and <paramref name="other"/>.
	/// </summary>
	/// <param name="other">The vector to subtract.</param>
	/// <returns>The resulting vector.</returns>
	public Vector2 Subtract(in Vector2 other) => new(X - other.X, Y - other.Y);


	/// <summary>
	/// Scales this vector by a scalar value.
	/// </summary>
	/// <param name="s">Scalar multiplier.</param>
	/// <returns>The scaled vector.</returns>
	public Vector2 Scale(double s) => new(X * s, Y * s);


	/// <summary>
	/// Adds two vectors.
	/// </summary>
	public static Vector2 operator +(Vector2 a, Vector2 b) => new(a.X + b.X, a.Y + b.Y);


	/// <summary>
	/// Subtracts the second vector from the first.
	/// </summary>
	public static Vector2 operator -(Vector2 a, Vector2 b) => new(a.X - b.X, a.Y - b.Y);


	/// <summary>
	/// Negates the vector.
	/// </summary>
	public static Vector2 operator -(Vector2 v) => new(-v.X, -v.Y);


	/// <summary>
	/// Multiplies a vector by a scalar.
	/// </summary>
	public static Vector2 operator *(Vector2 v, double s) => new(v.X * s, v.Y * s);


	/// <summary>
	/// Multiplies a scalar by a vector.
	/// </summary>
	public static Vector2 operator *(double s, Vector2 v) => new(v.X * s, v.Y * s);


	/// <summary>
	/// Divides a vector by a scalar.
	/// </summary>
	public static Vector2 operator /(Vector2 v, double s) => new(v.X / s, v.Y / s);


	/// <summary>
	/// Compares this vector to another within an optional epsilon.
	/// </summary>
	/// <param name="other">Other vector.</param>
	/// <returns>True if both components are within <paramref>
	///     <name>Geometry.Constants.PositionEpsilon</name>
	/// </paramref>
	/// ; otherwise false.</returns>
	public bool AlmostEquals(Vector2 other) => (Math.Abs(X - other.X) < PositionEpsilon) && (Math.Abs(Y - other.Y) < PositionEpsilon);


	/// <summary>
	/// Indicates whether this instance and another specified Vector2 object have the same value.
	/// Uses exact equality on the double components.
	/// </summary>
	/// <param name="other">The vector to compare with this instance.</param>
	/// <returns>True if <paramref name="other"/> has the same components as this instance.</returns>
	[SuppressMessage("ReSharper", "CompareOfFloatsByEqualityOperator")]
	public bool Equals(Vector2 other) => (X == other.X) && (Y == other.Y);


	/// <summary>
	/// Determines whether the specified object is equal to the current vector.
	/// </summary>
	/// <param name="obj">The object to compare with the current vector.</param>
	/// <returns>True if <paramref name="obj"/> is a <see cref="Vector2"/> and has the same components.</returns>
	public override bool Equals(object? obj) => obj is Vector2 v && Equals(v);


	/// <summary>
	/// Equality operator.
	/// </summary>
	public static bool operator ==(Vector2 a, Vector2 b) => a.Equals(b);


	/// <summary>
	/// Inequality operator.
	/// </summary>
	public static bool operator !=(Vector2 a, Vector2 b) => !a.Equals(b);


	/// <summary>
	/// Compute a hash code for this vector.
	/// </summary>
	/// <returns>A unique hash code for this vector.</returns>
	public override int GetHashCode() {
		// Combine hash codes of components in a simple, deterministic way.
		unchecked {
			int hash = 17;
			hash = (hash * 31) + X.GetHashCode();
			hash = (hash * 31) + Y.GetHashCode();

			return hash;
		}
	}


	/// <summary>
	/// Returns a string representation of the vector in the form (x, y) with 6 decimal places.
	/// </summary>
	/// <returns>A formatted string.</returns>
	public override string ToString() => $"({X:F6}, {Y:F6})";

}