// Port of concepts from Tactile (c) 2018 Craig S. Kaplan, BSD 3-Clause. See LICENSE.

using Microsoft.Extensions.Logging;

using TactileCs.Diagnostics;
using TactileCs.Geometry;


namespace TactileCs.Tiling.Analysis;


/// <summary>
/// Builds a graph view over the tiles generated by an <see cref="IsohedralTiling"/> inside a sampled region.
/// The graph can be queried for neighbors, distances, shortest paths, connected components, and nearest cells.
/// </summary>
public sealed class TilingGraph {

	static readonly ILogger<TilingGraph> _Logger = TactileLogger.CreateLogger<TilingGraph>();

	readonly Dictionary<int, List<TilingAdjacency>> _AdjacencyByCellId;
	readonly Dictionary<int, TilingCell>            _CellsById;
	readonly List<TilingAdjacency>                  _Connections;


	/// <summary>
	/// Gets the tiling instance used to generate the graph.
	/// </summary>
	public IsohedralTiling Tiling {
		get;
	}

	/// <summary>
	/// Gets the region that was sampled to create the graph.
	/// </summary>
	public TilingRegion Region {
		get;
	}

	/// <summary>
	/// Gets the cells included in the graph.
	/// </summary>
	public IReadOnlyList<TilingCell> Cells {
		get;
	}

	/// <summary>
	/// Gets the undirected adjacency relationships detected between sampled cells.
	/// </summary>
	public IReadOnlyList<TilingAdjacency> Connections => _Connections;


	/// <summary>
	/// Creates a graph view over a sampled tiling region.
	/// </summary>
	/// <param name="tiling">The tiling to analyze.</param>
	/// <param name="region">The region to sample.</param>
	/// <exception cref="ArgumentNullException">Thrown when <paramref name="tiling"/> is null.</exception>
	public TilingGraph(IsohedralTiling tiling, TilingRegion region) {
		ArgumentNullException.ThrowIfNull(tiling);

		Tiling      = tiling;
		Region      = region;

		_Logger.LogInformation("Building TilingGraph for region {Region}", region);

		using (PerformanceMonitor.Default.BeginOperation("TilingGraph.BuildCells"))
			Cells = BuildCells(tiling, region);

		_CellsById = Cells.ToDictionary(static cell => cell.Id);

		using (PerformanceMonitor.Default.BeginOperation("TilingGraph.BuildConnections"))
			_Connections = BuildConnections(Cells, out _AdjacencyByCellId);

		_Logger.LogInformation(
			"TilingGraph complete: {CellCount} cells, {ConnectionCount} connections",
			Cells.Count, _Connections.Count);
	}


	/// <summary>
	/// Returns the cell with the specified identifier, if present.
	/// </summary>
	/// <param name="cellId">Graph-local cell identifier.</param>
	/// <returns>The matching cell, or <c>null</c> when the identifier is unknown.</returns>
	public TilingCell? FindCell(int cellId) => _CellsById.GetValueOrDefault(cellId);


	/// <summary>
	/// Finds the sampled cell whose centroid is closest to the given point.
	/// </summary>
	/// <param name="point">The query point.</param>
	/// <returns>The nearest sampled cell, or <c>null</c> when the graph is empty.</returns>
	public TilingCell? FindNearestCell(Vector2 point) {
		TilingCell? closest             = null;
		double      closestDistanceSqr  = double.PositiveInfinity;

		foreach (TilingCell cell in Cells) {
			double distanceSquared = Vector2.DistanceSquared(cell.Center, point);

			if (distanceSquared < closestDistanceSqr) {
				closestDistanceSqr = distanceSquared;
				closest            = cell;
			}
		}

		return closest;
	}


	/// <summary>
	/// Returns the neighboring cells for the specified cell.
	/// </summary>
	/// <param name="cell">The source cell.</param>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts are included; otherwise, only edge-sharing neighbors are returned.
	/// </param>
	/// <returns>The neighboring cells.</returns>
	/// <exception cref="ArgumentNullException">Thrown when <paramref name="cell"/> is null.</exception>
	/// <exception cref="ArgumentException">Thrown when the cell does not belong to this graph.</exception>
	public IEnumerable<TilingCell> GetNeighbours(TilingCell cell, bool includeCornerNeighbours = false) {
		ArgumentNullException.ThrowIfNull(cell);
		EnsureGraphCell(cell);

		foreach (TilingAdjacency adjacency in GetAdjacencyList(cell.Id)) {
			if (!includeCornerNeighbours && !adjacency.SharesEdge) {
				continue;
			}

			yield return adjacency.Source.Id == cell.Id ? adjacency.Target : adjacency.Source;
		}
	}


	/// <summary>
	/// Returns the adjacency records for the specified cell.
	/// </summary>
	/// <param name="cell">The source cell.</param>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts are included; otherwise, only edge-sharing neighbors are returned.
	/// </param>
	/// <returns>The adjacency relationships incident to the cell.</returns>
	/// <exception cref="ArgumentNullException">Thrown when <paramref name="cell"/> is null.</exception>
	/// <exception cref="ArgumentException">Thrown when the cell does not belong to this graph.</exception>
	public IEnumerable<TilingAdjacency> GetAdjacencies(TilingCell cell, bool includeCornerNeighbours = false) {
		ArgumentNullException.ThrowIfNull(cell);
		EnsureGraphCell(cell);

		foreach (TilingAdjacency adjacency in GetAdjacencyList(cell.Id)) {
			if (includeCornerNeighbours || adjacency.SharesEdge) {
				yield return adjacency;
			}
		}
	}


	/// <summary>
	/// Computes the Euclidean distance between the centroids of two cells.
	/// </summary>
	/// <param name="first">The first cell.</param>
	/// <param name="second">The second cell.</param>
	/// <returns>The centroid-to-centroid distance.</returns>
	public double GetCentroidDistance(TilingCell first, TilingCell second) {
		ArgumentNullException.ThrowIfNull(first);
		ArgumentNullException.ThrowIfNull(second);
		EnsureGraphCell(first);
		EnsureGraphCell(second);

		return Vector2.Distance(first.Center, second.Center);
	}


	/// <summary>
	/// Computes the shortest hop distance between two cells using breadth-first search.
	/// </summary>
	/// <param name="start">The start cell.</param>
	/// <param name="target">The target cell.</param>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts are traversable; otherwise, only edge-sharing adjacencies are traversed.
	/// </param>
	/// <returns>
	/// The minimum number of graph edges between the cells, or <c>null</c> when no route exists.
	/// </returns>
	public int? GetHopDistance(TilingCell start, TilingCell target, bool includeCornerNeighbours = false) {
		IReadOnlyList<TilingCell> path = GetShortestPath(start, target, includeCornerNeighbours);

		return path.Count == 0 ? null : path.Count - 1;
	}


	/// <summary>
	/// Returns the cells that can be reached within the specified number of graph steps.
	/// </summary>
	/// <param name="origin">The starting cell.</param>
	/// <param name="steps">Maximum number of graph steps.</param>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts are traversable; otherwise, only edge-sharing adjacencies are traversed.
	/// </param>
	/// <returns>The reachable cells, including the origin cell.</returns>
	public IReadOnlyList<TilingCell> GetCellsWithinSteps(TilingCell origin, int steps, bool includeCornerNeighbours = false) {
		ArgumentNullException.ThrowIfNull(origin);
		EnsureGraphCell(origin);

		if (steps < 0) {
			throw new ArgumentOutOfRangeException(nameof(steps), "Step count must be non-negative.");
		}

		HashSet<int> visited = [origin.Id];
		Queue<(int cellId, int depth)> frontier = new();
		frontier.Enqueue((origin.Id, 0));

		while (frontier.Count > 0) {
			(int cellId, int depth) = frontier.Dequeue();

			if (depth == steps) {
				continue;
			}

			foreach (int neighbourId in EnumerateNeighbourIds(cellId, includeCornerNeighbours)) {
				if (visited.Add(neighbourId)) {
					frontier.Enqueue((neighbourId, depth + 1));
				}
			}
		}

		return visited.Select(id => _CellsById[id]).OrderBy(static cell => cell.Id).ToArray();
	}


	/// <summary>
	/// Computes the shortest path between two cells using breadth-first search.
	/// </summary>
	/// <param name="start">The start cell.</param>
	/// <param name="target">The target cell.</param>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts are traversable; otherwise, only edge-sharing adjacencies are traversed.
	/// </param>
	/// <returns>
	/// The ordered sequence of cells along the shortest path, including the start and target cells.
	/// An empty list is returned when no path exists.
	/// </returns>
	public IReadOnlyList<TilingCell> GetShortestPath(TilingCell start, TilingCell target, bool includeCornerNeighbours = false) {
		ArgumentNullException.ThrowIfNull(start);
		ArgumentNullException.ThrowIfNull(target);
		EnsureGraphCell(start);
		EnsureGraphCell(target);

		if (start.Id == target.Id) {
			return [start];
		}

		IReadOnlyList<TilingCell> path;
		using (PerformanceMonitor.Default.BeginOperation("TilingGraph.GetShortestPath")) {
			Queue<int> frontier = new();
			Dictionary<int, int?> previousByCellId = new() {
					[start.Id] = null
			};
			frontier.Enqueue(start.Id);

			while (frontier.Count > 0) {
				int currentId = frontier.Dequeue();

				foreach (int neighbourId in EnumerateNeighbourIds(currentId, includeCornerNeighbours)) {
					if (previousByCellId.ContainsKey(neighbourId)) {
						continue;
					}

					previousByCellId[neighbourId] = currentId;

					if (neighbourId == target.Id) {
						path = ReconstructPath(target.Id, previousByCellId);
						_Logger.LogDebug("Shortest path {Start}->{Target}: {Hops} hops",
							start.Id, target.Id, path.Count - 1);
						return path;
					}

					frontier.Enqueue(neighbourId);
				}
			}
		}

		_Logger.LogDebug("No path found {Start}->{Target}", start.Id, target.Id);
		return [];
	}


	/// <summary>
	/// Counts the connected components of the sampled graph.
	/// </summary>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts connect components; otherwise, only edge-sharing adjacencies connect components.
	/// </param>
	/// <returns>The number of connected components.</returns>
	public int GetConnectedComponentCount(bool includeCornerNeighbours = false) => GetConnectedComponents(includeCornerNeighbours).Count;


	/// <summary>
	/// Computes the connected components of the sampled graph.
	/// </summary>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts connect components; otherwise, only edge-sharing adjacencies connect components.
	/// </param>
	/// <returns>A list of connected components, each ordered by cell identifier.</returns>
	public IReadOnlyList<IReadOnlyList<TilingCell>> GetConnectedComponents(bool includeCornerNeighbours = false) {
		List<IReadOnlyList<TilingCell>> components = [];
		HashSet<int> visited = [];

		foreach (TilingCell cell in Cells) {
			if (!visited.Add(cell.Id)) {
				continue;
			}

			List<TilingCell> component = [];
			Queue<int> frontier = new();
			frontier.Enqueue(cell.Id);

			while (frontier.Count > 0) {
				int currentId = frontier.Dequeue();
				component.Add(_CellsById[currentId]);

				foreach (int neighbourId in EnumerateNeighbourIds(currentId, includeCornerNeighbours)) {
					if (visited.Add(neighbourId)) {
						frontier.Enqueue(neighbourId);
					}
				}
			}

			components.Add(component.OrderBy(static item => item.Id).ToArray());
		}

		return components;
	}


	/// <summary>
	/// Returns the degree of a cell within the graph.
	/// </summary>
	/// <param name="cell">The cell to inspect.</param>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts are included; otherwise, only edge-sharing neighbors are counted.
	/// </param>
	/// <returns>The number of adjacent cells.</returns>
	public int GetDegree(TilingCell cell, bool includeCornerNeighbours = false) =>
			GetNeighbours(cell, includeCornerNeighbours).Count();


	/// <summary>
	/// Builds a degree distribution for the current graph.
	/// </summary>
	/// <param name="includeCornerNeighbours">
	/// If <c>true</c>, corner-only contacts are included; otherwise, only edge-sharing neighbors are counted.
	/// </param>
	/// <returns>A dictionary keyed by degree, with values equal to the number of cells with that degree.</returns>
	public IReadOnlyDictionary<int, int> GetDegreeDistribution(bool includeCornerNeighbours = false) =>
			Cells.GroupBy(cell => GetDegree(cell, includeCornerNeighbours))
				 .OrderBy(static group => group.Key)
				 .ToDictionary(static group => group.Key, static group => group.Count());


	static List<TilingCell> BuildCells(IsohedralTiling tiling, TilingRegion region) {
		Polygon          prototype = tiling.GetTileShape();
		List<TilingCell> cells     = [];
		int              nextId    = 0;

		foreach ((Transform2D transform, int t1, int t2, int aspect) in tiling.FillRegionBounds(region.XMin, region.YMin, region.XMax, region.YMax)) {
			Polygon placedShape = prototype.Transform(transform);
			(double minX, double minY, double maxX, double maxY) = placedShape.BoundingBox();

			if (!region.Intersects(minX, minY, maxX, maxY, Constants.PositionEpsilon)) {
				continue;
			}

			cells.Add(new TilingCell(nextId++, transform, placedShape, placedShape.Centroid(), t1, t2, aspect));
		}

		return cells;
	}


	static List<TilingAdjacency> BuildConnections(IReadOnlyList<TilingCell> cells, out Dictionary<int, List<TilingAdjacency>> adjacencyByCellId) {
		adjacencyByCellId = cells.ToDictionary(static cell => cell.Id, static _ => new List<TilingAdjacency>());

		double                tolerance   = Constants.PositionEpsilon;
		double                toleranceSq = tolerance * tolerance;
		List<TilingAdjacency> result      = [];

		for (int i = 0; i < cells.Count; i++) {
			TilingCell first = cells[i];
			(double firstMinX, double firstMinY, double firstMaxX, double firstMaxY) = first.Shape.BoundingBox();

			for (int j = i + 1; j < cells.Count; j++) {
				TilingCell second = cells[j];
				(double secondMinX, double secondMinY, double secondMaxX, double secondMaxY) = second.Shape.BoundingBox();

				if (!BoxesIntersect(firstMinX, firstMinY, firstMaxX, firstMaxY, secondMinX, secondMinY, secondMaxX, secondMaxY, tolerance)) {
					continue;
				}

				int sharedVertexCount = CountSharedVertices(first.Shape, second.Shape, toleranceSq);

				if (sharedVertexCount == 0) {
					continue;
				}

				TilingAdjacency adjacency = new(first, second, sharedVertexCount >= 2, sharedVertexCount, Vector2.Distance(first.Center, second.Center));
				result.Add(adjacency);
				adjacencyByCellId[first.Id].Add(adjacency);
				adjacencyByCellId[second.Id].Add(adjacency);
			}
		}

		return result;
	}


	static bool BoxesIntersect(double firstMinX,
							   double firstMinY,
							   double firstMaxX,
							   double firstMaxY,
							   double secondMinX,
							   double secondMinY,
							   double secondMaxX,
							   double secondMaxY,
							   double tolerance) =>
			(firstMaxX >= (secondMinX - tolerance))
			&& (secondMaxX >= (firstMinX - tolerance))
			&& (firstMaxY >= (secondMinY - tolerance))
			&& (secondMaxY >= (firstMinY - tolerance));


	static int CountSharedVertices(Polygon first, Polygon second, double toleranceSq) {
		List<int> matchedVertexIndices = [];
		int       sharedVertexCount    = 0;

		for (int i = 0; i < first.Vertices.Count; i++) {
			Vector2 firstVertex = first.Vertices[i];

			for (int j = 0; j < second.Vertices.Count; j++) {
				if (matchedVertexIndices.Contains(j)) {
					continue;
				}

				Vector2 secondVertex = second.Vertices[j];

				if (Vector2.DistanceSquared(firstVertex, secondVertex) > toleranceSq) {
					continue;
				}

				matchedVertexIndices.Add(j);
				sharedVertexCount++;
				break;
			}
		}

		return sharedVertexCount;
	}


	void EnsureGraphCell(TilingCell cell) {
		if (!_CellsById.TryGetValue(cell.Id, out TilingCell? graphCell) || !ReferenceEquals(graphCell, cell)) {
			throw new ArgumentException("The specified cell does not belong to this graph.", nameof(cell));
		}
	}


	IEnumerable<int> EnumerateNeighbourIds(int cellId, bool includeCornerNeighbours) {
		foreach (TilingAdjacency adjacency in GetAdjacencyList(cellId)) {
			if (!includeCornerNeighbours && !adjacency.SharesEdge) {
				continue;
			}

			yield return adjacency.Source.Id == cellId ? adjacency.Target.Id : adjacency.Source.Id;
		}
	}


	IReadOnlyList<TilingAdjacency> GetAdjacencyList(int cellId) =>
			_AdjacencyByCellId.TryGetValue(cellId, out List<TilingAdjacency>? adjacencyList)
					? adjacencyList
					: [];


	IReadOnlyList<TilingCell> ReconstructPath(int targetId, IReadOnlyDictionary<int, int?> previousByCellId) {
		List<TilingCell> path = [];

		for (int? currentId = targetId; currentId is not null; currentId = previousByCellId[currentId.Value]) {
			path.Add(_CellsById[currentId.Value]);
		}

		path.Reverse();
		return path;
	}

}
