#region AutoGeneratedHeader

// TactileCs :: IsohedralTiling.cs last updated by: Ryan Hughes
// File last updated at: 20:19:43 on 02-12-2025
// Parent solution for file: TactileCs, file originally created at 20:12:42 on 02-12-2025 as part of project TactileCs.

#endregion


// Port of concepts from Tactile (c) 2018 Craig S. Kaplan, BSD 3-Clause. See LICENSE.

using System.Diagnostics;

using Microsoft.Extensions.Logging;

using TactileCs.Diagnostics;
using TactileCs.Geometry;


namespace TactileCs.Tiling;


/// <summary>
/// Isohedral tiling wrapper: holds type metadata, parameters, and prototile geometry.
/// Provides utilities to enumerate edge shapes, compute transforms for tiling,
/// and produce prototile polygon geometry for rendering and tiling algorithms.
/// </summary>
public sealed class IsohedralTiling {

	static readonly ILogger<IsohedralTiling> _Logger = TactileLogger.CreateLogger<IsohedralTiling>();

	/// <summary>
	/// Specification for a single prototile edge.
	/// Encodes the indices of the vertices that form the edge, the edge shape id,
	/// and whether the edge orientation is reversed relative to the canonical edge.
	/// </summary>
	/// <param name="v1">Index of the first vertex of the edge.</param>
	/// <param name="v2">Index of the second vertex of the edge.</param>
	/// <param name="shapeId">Identifier for the edge shape category (type-local).</param>
	/// <param name="rev">If true, the canonical orientation of the edge is reversed.</param>
	/// <remarks>
	/// Instances are small immutable descriptors used by the tiling type tables.
	/// </remarks>
	sealed class EdgeSpec(int v1, int v2, int shapeId, bool rev) {

		/// <summary>
		/// Gets the index of the first vertex of the edge.
		/// </summary>
		public int V1 {
			get;
		} = v1;

		/// <summary>
		/// Gets the index of the second vertex of the edge.
		/// </summary>
		public int V2 {
			get;
		} = v2;

		/// <summary>
		/// Gets the edge shape identifier.
		/// The meaning of this id is local to the tiling type.
		/// </summary>
		public int ShapeId {
			get;
		} = shapeId;

		/// <summary>
		/// Gets a value indicating whether the edge orientation is reversed.
		/// When true, the canonical edge direction is flipped.
		/// </summary>
		public bool Rev {
			get;
		} = rev;

	}


	/// <summary>
	/// Container for per-type static tiling metadata.
	/// Holds counts, arrays of edge specifications, default parameter vectors,
	/// and the symmetry group used to tile the plane.
	/// </summary>
	sealed class TilingTypeData {

		/// <summary>
		/// Gets the number of edges on the prototile.
		/// </summary>
		public int EdgeCount {
			get;
			init;
		}

		/// <summary>
		/// Gets the number of distinct edge shape categories used by the type.
		/// </summary>
		public int DistinctEdgeShapes {
			get;
			init;
		}

		/// <summary>
		/// Gets the number of vertices of the prototile.
		/// </summary>
		public int VertexCount {
			get;
			init;
		}

		/// <summary>
		/// Gets the array of <see cref="EdgeSpec"/> entries describing each edge.
		/// </summary>
		public EdgeSpec[]    Edges         { get; init; } = [];

		/// <summary>
		/// Gets the default parameter vector for the tiling type.
		/// These parameters are used by the per-type geometry logic to compute vertices.
		/// </summary>
		public double[]      DefaultParams { get; init; } = [];

		/// <summary>
		/// Gets the symmetry group used to generate the tiling lattice for this type.
		/// </summary>
		public SymmetryGroup Symmetry      { get; init; } = new(new Vector2(1, 0), new Vector2(0, 1));

	}


	/// <summary>
	/// Registry mapping isohedral type id to its <see cref="TilingTypeData"/>.
	/// Contains built-in type definitions (currently minimal stubs).
	/// </summary>
	readonly static Dictionary<int, TilingTypeData> _TilingTypes = new();


	/// <summary>
	/// Static initializer populates the built-in tiling type table.
	/// This currently includes minimal example entries and should be extended
	/// with the full set of isohedral type data from the original Tactile tables.
	/// </summary>
	static IsohedralTiling() {
		// TODO: extend this table to all isohedral types from the original Tactile data.

		// Example: Type 1 – simple parallelogram tiling as a stub.
		_TilingTypes[1] = new TilingTypeData {
				EdgeCount          = 4,
				DistinctEdgeShapes = 1,
				VertexCount        = 4,
				Edges              = [new EdgeSpec(0, 1, 0, false), new EdgeSpec(1, 2, 0, false), new EdgeSpec(2, 3, 0, false), new EdgeSpec(3, 0, 0, false)],
				DefaultParams      = [],
				Symmetry           = new SymmetryGroup(new Vector2(1, 0), new Vector2(0, 1))
		};
	}


	/// <summary>
	/// Gets the isohedral tiling type identifier for this instance.
	/// </summary>
	public int TypeId {
		get;
		private set;
	}

	/// <summary>
	/// Backing data for the current tiling type. Null until <see cref="SetType"/> is called.
	/// </summary>
	TilingTypeData? _Data;

	/// <summary>
	/// Current parameter vector for the tiling. Always a clone of the underlying default
	/// vector when <see cref="_Data"/> is set.
	/// </summary>
	double[]        _Parameters = [];

	/// <summary>
	/// Computed prototile vertices (in order). Populated by <see cref="ComputeVertices"/>.
	/// </summary>
	Vector2[]       _Vertices   = [];

	/// <summary>
	/// Gets the number of parameters required by the current tiling type.
	/// </summary>
	/// <value>The length of the parameter vector.</value>
	public int NumParameters {
		get {
			return _Parameters.Length;
		}
	}


	/// <summary>
	/// Creates a new <see cref="IsohedralTiling"/> instance set to the given type id.
	/// </summary>
	/// <param name="typeId">Isohedral type identifier. Must be present in the internal type table.</param>
	/// <exception cref="ArgumentException">Thrown if <paramref name="typeId"/> is not defined in the registry.</exception>
	public IsohedralTiling(int typeId) {
		SetType(typeId);
	}


	/// <summary>
	/// Set the isohedral tiling type for this instance.
	/// Updates internal metadata and resets the parameter vector to the type's defaults,
	/// then recomputes prototile vertices.
	/// </summary>
	/// <param name="typeId">Type identifier to set.</param>
	/// <exception cref="ArgumentException">Thrown if the type id is not defined.</exception>
	public void SetType(int typeId) {
		if (!_TilingTypes.TryGetValue(typeId, out TilingTypeData? data)) {
			throw new ArgumentException($"Tiling type {typeId} is not defined.", nameof(typeId));
		}

		_Logger.LogInformation("SetType: switching to type {TypeId}", typeId);

		TypeId      = typeId;
		_Data       = data;
		_Parameters = (double[])_Data.DefaultParams.Clone();
		ComputeVertices();
	}


	/// <summary>
	/// Returns a cloned copy of the current parameter vector.
	/// Modifying the returned array does not affect the tiling instance.
	/// </summary>
	/// <returns>A new array containing the parameter values.</returns>
	public double[] GetParameters() => (double[])_Parameters.Clone();


	/// <summary>
	/// Replace the current parameter vector with the values provided and recompute vertices.
	/// </summary>
	/// <param name="values">Parameter values. Must match the expected parameter count for the current type.</param>
	/// <exception cref="ArgumentException">Thrown if <paramref name="values"/> length does not match the expected parameter count.</exception>
	public void SetParameters(ReadOnlySpan<double> values) {
		if (values.Length != _Parameters.Length) {
			throw new ArgumentException("Parameter length mismatch.", nameof(values));
		}

		values.CopyTo(_Parameters);
		ComputeVertices();
	}


	/// <summary>
	/// Returns the number of distinct edge shape categories for the current type.
	/// </summary>
	/// <returns>Count of distinct edge shapes.</returns>
	public int NumEdgeShapes() {
		Debug.Assert(_Data != null, nameof(_Data) + " != null");

		return _Data.DistinctEdgeShapes;
	}


	/// <summary>
	/// Gets the <see cref="SymmetryGroup"/> associated with the current tiling type.
	/// </summary>
	/// <remarks>Accessing this property requires a set tiling type.</remarks>
	public SymmetryGroup Symmetry {
		get {
			Debug.Assert(_Data != null, nameof(_Data) + " != null");

			return _Data.Symmetry;
		}
	}


	/// <summary>
	/// Compute the prototile vertex positions from the current parameter vector and
	/// the constraints encoded for the chosen isohedral type.
	/// </summary>
	/// <remarks>
	/// The real per-type geometry logic belongs here. Currently provides a minimal stub:
	/// type 1 is a unit square/parallelogram and other types place all vertices at origin.
	/// </remarks>
	void ComputeVertices() {
		Debug.Assert(_Data != null, nameof(_Data) + " != null");

		_Vertices = new Vector2[_Data.VertexCount];

		// IMPORTANT:
		// This is where the real per-type geometry logic goes, using the parameter vector
		// and the constraints encoded in the original Tactile data.
		// For now, we provide minimal stubs for demonstration.

		if (TypeId == 1) {
			// Unit square/parallelogram.
			_Vertices[0] = new Vector2(0, 0);
			_Vertices[1] = new Vector2(1, 0);
			_Vertices[2] = new Vector2(1, 1);
			_Vertices[3] = new Vector2(0, 1);
		}
		else {
			// Placeholder: all at origin.
			for (int i = 0; i < _Vertices.Length; i++) {
				_Vertices[i] = new Vector2(0, 0);
			}
		}
	}


	/// <summary>
	/// Compute an affine transform that maps the canonical unit-edge from (0,0)-(1,0)
	/// to the edge between points <paramref name="p"/> and <paramref name="q"/>.
	/// </summary>
	/// <param name="p">Start point of the target edge.</param>
	/// <param name="q">End point of the target edge.</param>
	/// <param name="rev">If true, compute the transform for the reversed canonical orientation
	/// (so canonical (0,0)->(1,0) maps to q->p).</param>
	/// <returns>A <see cref="Transform2D"/> that maps canonical edge coordinates into the tile's edge.</returns>
	static Transform2D ComputeEdgeTransform(Vector2 p, Vector2 q, bool rev) {
		Vector2 v   = q - p;
		double  len = v.Length;

		if (len < 1e-12) {
			return Transform2D.Identity;
		}

		double cos = v.X / len;
		double sin = v.Y / len;

		return !rev
				?

				// (0,0)->p, (1,0)->q
				new Transform2D(len * cos, -len * sin, p.X, len * sin, len * cos, p.Y)
				:

				// reversed orientation: (0,0)->q, (1,0)->p
				new Transform2D(-len * cos, len * sin, q.X, -len * sin, -len * cos, q.Y);
	}


	/// <summary>
	/// Iterate over each prototile edge and yield its shape data.
	/// The yielded tuple contains:
	/// - id: the edge shape identifier,
	/// - shape: the categorized edge shape (enum),
	/// - rev: whether the edge orientation is reversed,
	/// - T: a transform mapping the canonical edge to the tile edge.
	/// </summary>
	/// <returns>An enumerable of tuples describing each edge's shape and transform.</returns>
	public IEnumerable<(int id, EdgeShape shape, bool rev, Transform2D T)> ShapeEdges() {
		Debug.Assert(_Data != null, nameof(_Data) + " != null");

		for (int ei = 0; ei < _Data.EdgeCount; ei++) {
			EdgeSpec    e = _Data.Edges[ei];
			Vector2     p = _Vertices[e.V1];
			Vector2     q = _Vertices[e.V2];
			Transform2D t = ComputeEdgeTransform(p, q, e.Rev);

			// In a full port, edge shape category comes from the tiling type tables.
			EdgeShape shapeType = EdgeShape.J;

			yield return (e.ShapeId, shapeType, e.Rev, t);
		}
	}


	/// <summary>
	/// Variant of <see cref="ShapeEdges"/> that splits U/S edges into two halves.
	/// For U/S edges two tuples are yielded (first half, second half) with the
	/// <c>second</c> boolean indicating whether the yielded transform corresponds
	/// to the second half of the original edge.
	/// </summary>
	/// <returns>An enumerable of tuples describing each edge part's id, shape, orientation and transform.</returns>
	public IEnumerable<(int id, EdgeShape shape, bool rev, bool second, Transform2D T)> ShapeEdgeParts() {
		foreach ((int id, EdgeShape shape, bool rev, Transform2D fullT) in ShapeEdges()) {
			if (shape is EdgeShape.U or EdgeShape.S) {
				Vector2 p = fullT.Apply(new Vector2(0.0, 0.0));
				Vector2 m = fullT.Apply(new Vector2(0.5, 0.0));
				Vector2 q = fullT.Apply(new Vector2(1.0, 0.0));

				Transform2D firstHalf  = ComputeEdgeTransform(p, m, false);
				Transform2D secondHalf = ComputeEdgeTransform(m, q, false);

				yield return (id, shape, rev, false, firstHalf);
				yield return (id, shape, rev, true, secondHalf);
			}
			else {
				yield return (id, shape, rev, false, fullT);
			}
		}
	}


	/// <summary>
	/// Return a <see cref="Polygon"/> instance representing the prototile polygon,
	/// constructed from the currently computed vertex array.
	/// </summary>
	/// <returns>A polygon describing the prototile shape in local coordinates.</returns>
	public Polygon GetTileShape() => new(_Vertices);


	/// <summary>
	/// Generate transforms for tiles whose bounding boxes intersect the given region.
	/// Each yielded tuple includes the transform to place the prototile, and lattice
	/// indices/aspect values (currently placeholder zeros).
	/// </summary>
	/// <param name="xMin">Minimum x of the region to fill.</param>
	/// <param name="yMin">Minimum y of the region to fill.</param>
	/// <param name="xMax">Maximum x of the region to fill.</param>
	/// <param name="yMax">Maximum y of the region to fill.</param>
	/// <returns>An enumerable of tuples: transform, lattice index t1, t2, and aspect.</returns>
	/// <remarks>
	/// Note: the current implementation does not track lattice indices/aspect precisely
	/// and returns zeros for those values. The symmetry group's FillRegion implementation
	/// drives the transforms returned.
	/// </remarks>
	public IEnumerable<(Transform2D T, int t1, int t2, int aspect)> FillRegionBounds(double xMin, double yMin, double xMax, double yMax) {
		// For now, don't track lattice indices/aspect precisely – just return 0s.
		Debug.Assert(_Data != null, nameof(_Data) + " != null");

		_Logger.LogDebug("FillRegionBounds: [{XMin},{YMin}]→[{XMax},{YMax}]", xMin, yMin, xMax, yMax);

		using var timer = PerformanceMonitor.Default.BeginOperation("IsohedralTiling.FillRegionBounds");

		foreach (Transform2D t in _Data.Symmetry.FillRegion(xMin, yMin, xMax, yMax)) {
			yield return (t, 0, 0, 0);
		}
	}


	/// <summary>
	/// Return a colour index for a tile given lattice indices and an aspect.
	/// The mapping is a simple deterministic function suitable for quick colouring.
	/// </summary>
	/// <param name="t1">First lattice index.</param>
	/// <param name="t2">Second lattice index.</param>
	/// <param name="aspect">Aspect identifier for the tile.</param>
	/// <returns>An integer colour index (small non-negative integer).</returns>
	public int GetColour(int t1, int t2, int aspect) => (t1 + (2 * t2) + aspect) % 3;


	/// <summary>
	/// Builds a graph view over the tiles that intersect the given axis-aligned region.
	/// </summary>
	/// <param name="xMin">Minimum X coordinate of the region to sample.</param>
	/// <param name="yMin">Minimum Y coordinate of the region to sample.</param>
	/// <param name="xMax">Maximum X coordinate of the region to sample.</param>
	/// <param name="yMax">Maximum Y coordinate of the region to sample.</param>
	/// <returns>A graph wrapper that exposes cell adjacency and analysis queries.</returns>
	public Analysis.TilingGraph CreateGraph(double xMin, double yMin, double xMax, double yMax) => new(this, new Analysis.TilingRegion(xMin, yMin, xMax, yMax));

}
