#region AutoGeneratedHeader

// TactileCs :: Symmetry.cs last updated by: Ryan Hughes
// File last updated at: 20:15:07 on 02-12-2025
// Parent solution for file: TactileCs, file originally created at 20:12:07 on 02-12-2025 as part of project TactileCs.

#endregion


// Port of concepts from Tactile (c) 2018 Craig S. Kaplan, BSD 3-Clause. See LICENSE.

using TactileCs.Geometry;


namespace TactileCs.Tiling;


/// <summary>
/// Edge symmetry category (J, U, S, I) as in Tactile.
/// </summary>
public enum EdgeShape {

	/// <summary>J-edge: free, no symmetry constraint.</summary>
	J,

	/// <summary>U-edge: reflection symmetry about the midpoint of the edge.</summary>
	U,

	/// <summary>S-edge: 180° rotational symmetry.</summary>
	S,

	/// <summary>I-edge: invariant under both reflection and 180° rotation (straight edge).</summary>
	I

}


/// <summary>
/// Wallpaper symmetry group data: two lattice vectors + optional rotation count.
/// Mirrors/glides can be handled via edge pairing/flags.
/// </summary>
public sealed class SymmetryGroup {

	public Vector2 LatticeVector1 {
		get;
	}

	public Vector2 LatticeVector2 {
		get;
	}

	public int RotationCount {
		get;
	}


	public SymmetryGroup(Vector2 v1, Vector2 v2, int rotationCount = 1) {
		LatticeVector1 = v1;
		LatticeVector2 = v2;
		RotationCount  = rotationCount;
	}


	/// <summary>
	/// Generate approximate transforms covering an axis-aligned region.
	/// This is conservative: may generate tiles slightly outside bounds.
	/// </summary>
	public IEnumerable<Transform2D> FillRegion(double xMin, double yMin, double xMax, double yMax) {
		// Heuristic index ranges; can be refined later.
		const int iMin = -10;
		const int iMax = 10;
		const int jMin = -10;
		const int jMax = 10;

		for (int i = iMin; i <= iMax; i++) {
			for (int j = jMin; j <= jMax; j++) {
				Vector2     tVec  = (i * LatticeVector1) + (j * LatticeVector2);
				Transform2D baseT = new(1, 0, tVec.X, 0, 1, tVec.Y);

				if (RotationCount <= 1) {
					yield return baseT;

					continue;
				}

				double dTheta = 2 * Math.PI / RotationCount;

				for (int k = 0; k < RotationCount; k++) {
					double      theta = k * dTheta;
					double      cos   = Math.Cos(theta);
					double      sin   = Math.Sin(theta);
					Transform2D rot   = new(cos, -sin, 0, sin, cos, 0);

					yield return Transform2D.Multiply(baseT, rot);
				}
			}
		}
	}

}
